swagger: "2.0"
info:
  title: Healthcare Booking API
  description: Backend API Documentation for Healthcare Management System
  version: "1.0.0"

host: localhost:3000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: User Registration
      description: Register a new user account
      parameters:
        - in: body
          name: body
          required: true
          schema:
            required:
              - full_name
              - email
              - password
            properties:
              full_name:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        201:
          description: User registered successfully
        400:
          description: Email already exists

  /auth/login:
    post:
      tags:
        - Auth
      summary: User Login
      description: Login and receive a JWT token
      parameters:
        - in: body
          name: body
          required: true
          schema:
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: Login successful
        400:
          description: Invalid credentials

  /auth/me:
    get:
      tags:
        - Auth
      summary: Get current authenticated user
      description: Returns current user's id, email, and role
      responses:
        200:
          description: Current user details
        401:
          description: Unauthorized access

  /doctors/:
    get:
      tags:
        - Doctors
      summary: List all doctors
      description: Retrieve a list of all available doctors
      responses:
        200:
          description: List of doctors

  /recommend/:
    post:
      tags:
        - Recommendation
      summary: AI-Based Doctor Recommendation based on Symptoms
      description: Accepts user-described symptoms and returns a list of recommended doctor specializations using OpenAI GPT model.
      parameters:
        - in: body
          name: body
          required: true
          schema:
            required:
              - problem
            properties:
              problem:
                type: string
                example: "I have chest pain and shortness of breath."
      responses:
        200:
          description: Recommended specializations based on symptoms
          schema:
            type: object
            properties:
              problem:
                type: string
              recommended_specializations:
                type: array
                items:
                  type: string
        400:
          description: Problem description is required
        429:
          description: Rate limit exceeded. Too many requests in a short time.

  /appointments/:
    post:
      tags:
        - Appointments
      summary: Book an appointment
      description: Create a new appointment with a doctor for a selected time slot
      parameters:
        - in: body
          name: body
          required: true
          schema:
            required:
              - doctor_id
              - appointment_time
            properties:
              doctor_id:
                type: integer
              appointment_time:
                type: string
                format: date-time
      responses:
        201:
          description: Appointment booked successfully
        400:
          description: Missing or invalid fields
        409:
          description: Time slot already booked

  /appointments/me:
    get:
      tags:
        - Appointments
      summary: View my appointments
      description: Retrieve a list of all appointments booked by the authenticated user
      responses:
        200:
          description: List of user's own appointments

  /appointments/{appointment_id}/cancel:
    put:
      tags:
        - Appointments
      summary: Cancel an appointment
      description: Soft cancel an appointment by updating its status
      parameters:
        - in: path
          name: appointment_id
          required: true
          type: integer
      responses:
        200:
          description: Appointment cancelled successfully
        404:
          description: Appointment not found

  /appointments/{appointment_id}/complete:
    put:
      tags:
        - Appointments
      summary: Mark an appointment as completed
      description: Mark an existing appointment as completed
      parameters:
        - in: path
          name: appointment_id
          required: true
          type: integer
      responses:
        200:
          description: Appointment marked as completed
        404:
          description: Appointment not found
