"""add named foreign key constraint to appointments

Revision ID: 2500bf3ef8f5
Revises: 1708ac085728
Create Date: 2025-04-25 20:13:11.990892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2500bf3ef8f5'
down_revision = '1708ac085728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_appointment_doctor_id', 'doctor', ['doctor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointment_doctor_id', type_='foreignkey')

    # ### end Alembic commands ###
